//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanDetail()
        {
            this.PrimaryLoans = new HashSet<PrimaryLoan>();
        }
    
        public int DetailsID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> PreviousLoans { get; set; }
        public string Loan_Purpose { get; set; }
        public string Borrower { get; set; }
        public string Business_Sector { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string Risk_category { get; set; }
        public Nullable<double> Estimated_annual_default_rate { get; set; }
        public string Collateral { get; set; }
        public string Valuation { get; set; }
        public string Personal_guarantee { get; set; }
        public Nullable<System.DateTime> Registered { get; set; }
        public string Invoice_Transaction { get; set; }
        public string Invoice_Recourse { get; set; }
        public string Real_Estate_Type { get; set; }
        public string Size { get; set; }
        public string VAT_Country { get; set; }
        public string Liability { get; set; }
        public string Pledge_Type { get; set; }
        public string Occupation { get; set; }
        public string Dependents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryLoan> PrimaryLoans { get; set; }
    }
}
