//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MintosEntities : DbContext
    {
        public MintosEntities()
            : base("name=MintosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoanDetail> LoanDetails { get; set; }
        public virtual DbSet<PrimaryLoan> PrimaryLoans { get; set; }
        public virtual DbSet<InformationToAdd> InformationToAdds { get; set; }
    }
}
