//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryLoan
    {
        public string Country { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public Nullable<System.DateTime> Closing_Date { get; set; }
        public string Loan_Type { get; set; }
        public string Amortization_Method { get; set; }
        public string Loan_Originator { get; set; }
        public Nullable<decimal> Loan_Amount { get; set; }
        public Nullable<decimal> Remaining_Principal { get; set; }
        public Nullable<decimal> LTV { get; set; }
        public Nullable<decimal> Interest_Rate { get; set; }
        public string Term { get; set; }
        public Nullable<int> Payments_Received { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount_Available_for_Investment { get; set; }
        public string Buyback_Guarantee { get; set; }
        public Nullable<decimal> My_Investments { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Borrower_APR { get; set; }
        public Nullable<int> Detail_ID { get; set; }
    
        public virtual LoanDetail LoanDetail { get; set; }
    }
}
